// Trade orchestrator — sequences engine/trade.js's pure functions, mirrors
// turnMachine.js's own relationship to engine/auction.js exactly (compute in
// the engine layer, apply the mutations here). ACCEPT_TRADE's money
// transfers go through economy/applyTransaction.js directly, one call per
// direction — the same pattern turnMachine.js's own settleDebt() (rent)
// already uses, NOT turnMachine.js's applyIntents (its ADD_MONEY/
// REMOVE_MONEY are hard-coded Bank-mediated, wrong for a direct
// player-to-player trade payment — see engine/trade.js's acceptTrade
// docstring). Pure function: no I/O, no internal randomness or wall-clock
// reads — `now` and every fresh id (tradeId/newTradeId) always arrive as
// inputs, generated by the impure Socket.IO layer
// (infrastructure/websocket/socketServer.js), never here.
//
// Deliberately NOT part of turnMachine.js / VALID_ACTIONS_BY_PHASE — three
// architecture questions came up wiring the full trade system (asset
// locking, expiration, and this one) and were confirmed explicitly before
// any code was written, not guessed:
//
// 1. Trade actions are independent of gameState.phase. Every other action
//    in this backend is implicitly "the current-turn player, during a
//    specific phase" (turnMachine.js's own file header). A trade is
//    fundamentally different — either player, at any point in the match,
//    regardless of whose turn it is or what phase the game is in, matching
//    how trading actually works and GAME_DESIGN_SPEC.md §10's own framing
//    ("Player-to-player trading was named in the architecture doc's event
//    catalog... the detailed ruleset... is not specified here"). Routing
//    these through turnMachine.js's phase-gated VALID_ACTIONS_BY_PHASE would
//    have meant either inventing an artificial restriction nobody asked for
//    (only tradeable during the current player's own POST_ACTIONS window)
//    or distorting the phase machine for an action type it was never
//    designed to gate. This file is the alternative applyTradeAction()
//    entry point infrastructure/websocket/socketServer.js's handleGameAction
//    routes to instead of transitionTurn() whenever actionType is one of
//    the five below — same generic C2S_GAME_ACTION envelope, same
//    applyWithIdempotency wrapper (confirmed genuinely generic — its own
//    header: "wraps any transition function shaped (gameState, action) ->
//    {gameState, transactions}... never imports turnMachine.js"), just a
//    different transitionFn. turnMachine.js itself is completely untouched
//    by any of this — this file imports economy/applyTransaction.js
//    directly, not turnMachine.js.
//
// 2. Asset locking is computed on the fly from GameState.pendingTrades, not
//    a persisted `locked` column — see engine/trade.js's header. No
//    migration, no DATABASE_DESIGN.md schema change.
//
// 3. Expiration is a lazy check, not a new timer. stateMachine/timers.js's
//    TimerManager tracks "at most one active timer per room" (its own
//    documented invariant) — a room can have several concurrent trades,
//    each with its own independent deadline, which that model can't express
//    without a real rework of an already-shipped, already-tested module.
//    Instead, every trade action first prunes any trade past its expiresAt
//    from pendingTrades (pruneExpiredTrades, below) before doing anything
//    else — an expired trade someone tries to act on simply isn't found
//    (TRADE_NOT_FOUND), and one nobody ever touches again just sits inert
//    until the next unrelated trade action sweeps it, which is harmless.

import { proposeTrade, counterTrade, acceptTrade, InvalidTradeError } from '../engine/trade.js';
import { applyTransaction } from '../economy/applyTransaction.js';

export const TRADE_ACTION_TYPES = Object.freeze(['PROPOSE_TRADE', 'COUNTER_TRADE', 'ACCEPT_TRADE', 'REJECT_TRADE', 'CANCEL_TRADE']);

/**
 * Trades past their expiresAt, dropped. Called at the top of every trade
 * action — see this file's header, point 3.
 * @param {import('../domain/trade.js').Trade[]} pendingTrades
 * @param {string} now - ISO timestamp
 * @returns {import('../domain/trade.js').Trade[]}
 */
export function pruneExpiredTrades(pendingTrades, now) {
  const nowMs = new Date(now).getTime();
  return pendingTrades.filter((trade) => new Date(trade.expiresAt).getTime() > nowMs);
}

function findTrade(pendingTrades, tradeId) {
  const trade = pendingTrades.find((t) => t.id === tradeId);
  if (!trade) {
    throw new InvalidTradeError('TRADE_NOT_FOUND', `Trade '${tradeId}' does not exist, has already resolved, or has expired`);
  }
  return trade;
}

/**
 * The single entry point for all five trade actions — same shape
 * turnMachine.js's transitionTurn has ((gameState, action, now) -> result),
 * so infrastructure/websocket/socketServer.js can bind it into
 * applyWithIdempotency exactly like transitionTurn, just without a
 * boardTiles argument (trade never needs tile data).
 * @param {import('../domain/gameState.js').GameState} gameState
 * @param {{ type: string, payload: object }} action
 * @param {string} now - ISO timestamp
 * @returns {{ gameState: import('../domain/gameState.js').GameState, transactions: object[] }}
 */
export function applyTradeAction(gameState, action, now) {
  const live = pruneExpiredTrades(gameState.pendingTrades, now);
  const { type, payload } = action;

  switch (type) {
    case 'PROPOSE_TRADE': {
      const trade = proposeTrade({
        id: payload.tradeId,
        roomId: gameState.roomId,
        gameState,
        pendingTrades: live,
        proposerId: payload.playerId,
        targetId: payload.targetId,
        proposerOffer: payload.proposerOffer,
        targetOffer: payload.targetOffer,
        now,
      });
      return { gameState: { ...gameState, pendingTrades: [...live, trade] }, transactions: [] };
    }

    case 'COUNTER_TRADE': {
      const existing = findTrade(live, payload.tradeId);
      if (payload.playerId !== existing.targetId) {
        throw new InvalidTradeError('NOT_TARGET', `Only '${existing.targetId}' may counter trade '${existing.id}'`);
      }
      const remaining = live.filter((t) => t.id !== existing.id);
      const countered = counterTrade({
        id: payload.newTradeId,
        gameState,
        pendingTrades: remaining,
        existingTrade: existing,
        counterOffer: { proposerOffer: payload.proposerOffer, targetOffer: payload.targetOffer },
        now,
      });
      return { gameState: { ...gameState, pendingTrades: [...remaining, countered] }, transactions: [] };
    }

    case 'ACCEPT_TRADE': {
      const trade = findTrade(live, payload.tradeId);
      const remaining = live.filter((t) => t.id !== trade.id);
      const { moneyTransfers, propertyTransfers } = acceptTrade({
        gameState,
        pendingTrades: remaining,
        trade,
        actorId: payload.playerId,
      });

      // Direct player-to-player transfers via applyTransaction, one call
      // per direction — see engine/trade.js's acceptTrade docstring for why
      // this is NOT turnMachine.js's applyIntents (that vocabulary's
      // ADD_MONEY/REMOVE_MONEY are Bank-mediated, wrong for a trade
      // payment). Same pattern turnMachine.js's settleDebt() already uses
      // for rent. Note (finding #15/#20, PROJECT_STATUS.md): a trade with
      // money offered on *both* sides calls applyTransaction twice before
      // the idempotency layer's single end-of-action stateVersion bump —
      // the already-documented idempotencyKey collision gap, now reachable
      // here for real, not just latent as it was through auction settlement.
      let state = { ...gameState, pendingTrades: remaining };
      const transactions = [];
      for (const transfer of moneyTransfers) {
        const { gameState: next, transaction } = applyTransaction(state, { ...transfer, transactionType: 'trade' });
        state = next;
        transactions.push(transaction);
      }

      const properties = state.properties.map((property) => {
        const transfer = propertyTransfers.find((t) => t.propertyId === property.id);
        return transfer ? { ...property, ownerId: transfer.toPlayerId } : property;
      });

      return { gameState: { ...state, properties }, transactions };
    }

    case 'REJECT_TRADE': {
      const trade = findTrade(live, payload.tradeId);
      if (payload.playerId !== trade.targetId) {
        throw new InvalidTradeError('NOT_TARGET', `Only '${trade.targetId}' may reject trade '${trade.id}'`);
      }
      return { gameState: { ...gameState, pendingTrades: live.filter((t) => t.id !== trade.id) }, transactions: [] };
    }

    case 'CANCEL_TRADE': {
      const trade = findTrade(live, payload.tradeId);
      if (payload.playerId !== trade.proposerId) {
        throw new InvalidTradeError('NOT_PROPOSER', `Only '${trade.proposerId}' may cancel trade '${trade.id}'`);
      }
      return { gameState: { ...gameState, pendingTrades: live.filter((t) => t.id !== trade.id) }, transactions: [] };
    }

    default:
      // Exhaustiveness guard, same convention as turnMachine.js's
      // resolveLanding/applyIntents — unreachable given
      // socketServer.js only routes TRADE_ACTION_TYPES here.
      throw new Error(`applyTradeAction: unhandled action type '${type}'`);
  }
}
